### ISSUE TITLE
Reset on Esc?

### ISSUE THREAD

**Issue by mxmilkiib** [gnusenpai/colemakclub#27]
Like Monkeytype?

**Comment by sebastiancarlos** [comment]
I like the idea!

My two cents: I would prefer to have reset on `tab` rather than `esc`. 

I suggest it because `tab` would match a bit more the current behavior of MonkeyType. And, like you, I think there's some value in preserving muscle memory across all the typing applications if possible.

It is true, `esc` can be configured as a "quick restart" key on MonkeyType [0], but that seems to be the most disruptive option because it changes the command line key from its default `esc`. Additionally, the default way of reseting is to press `tab + enter` [1], which again seems to suggest that `tab` is the default key for that action.

0: 
<img width="517" alt="Screenshot 2022-10-23 at 09 46 35" src="https://user-images.githubusercontent.com/88276600/197380951-58aa5707-1371-4116-91ac-ae4cd794d55a.png">

1:
<img width="356" alt="Screenshot 2022-10-23 at 09 46 17" src="https://user-images.githubusercontent.com/88276600/197380960-0e4c0eb6-eb98-416f-87b2-3e1f003938e0.png">

**Comment by mxmilkiib** [comment]
Ah yes, I have that turned on. Esc is easier to hit, on my keyboard anyway (it's under my left thumb).

The biggest reason in my mind, re a standard keyboard, is that Tab is at the end of as row of letter keys, so easier to press by accident.
